---
title: 异常
slug: 异常
sidebar_position: 3
---


# 异常

异常

## 异常的分类

                     ┌───────────┐

                     │  Object   │

                     └───────────┘

                           ▲

                           │

                     ┌───────────┐

                     │ Throwable │

                     └───────────┘

                           ▲

                 ┌─────────┴─────────┐

                 │                   │

           ┌───────────┐       ┌───────────┐

           │   Error   │       │ Exception │

           └───────────┘       └───────────┘

                 ▲                   ▲

         ┌───────┘              ┌────┴──────────┐

         │                      │               │

┌─────────────────┐    ┌─────────────────┐┌───────────┐

│OutOfMemoryError │... │RuntimeException ││IOException│...

└─────────────────┘    └─────────────────┘└───────────┘

                                ▲

                    ┌───────────┴─────────────┐

                    │                         │

         ┌─────────────────────┐ ┌─────────────────────────┐

         │NullPointerException │ │IllegalArgumentException │...

         └─────────────────────┘ └─────────────────────────┘

## Error

Error类及其子类是用来描述Java运行中内部错误以及资源耗尽的错误，不可解决；

例如：

- OutOfMemoryError：内存耗尽
- NoClassDefFoundError：无法加载某个Class
- StackOverflowError：栈溢出

## Exception

Exception类，非致命性错误，可以通过捕捉处理使程序继续执行

某些异常是应用程序逻辑处理的一部分，应该捕获并处理。

例如：

- NumberFormatException：数值类型的格式错误
- FileNotFoundException：未找到文件
- SocketException：读取网络失败

还有一些异常是程序逻辑编写不对造成的，应该修复程序本身。

例如：

- NullPointerException：对某个null的对象调用方法或字段
- IndexOutOfBoundsException：数组索引越界

Exception又分为两大类：

- RuntimeException（运行时异常）以及它的子类；
- 非RuntimeException（包括IOException、ReflectiveOperationException等等）Java规定：
- 必须捕获的异常，包括Exception及其子类，但不包括RuntimeException及其子类，这种类型的异常称为Checked Exception。
- 不需要捕获的异常，包括Error及其子类，RuntimeException及其子类。

# 捕捉异常

- 自动捕捉异常
- try catch语句捕捉异常

```
try{
    //被捕捉的代码
}catch(/*异常类型*/ e){
    //对异常的处理
}
多重try-catch代码块
try{
    //语句1；
    //语句2；
}
catch(some Exception1 e){
    
}
catch(some Exception2 e){
    
}
catch(some Exception3 e){
    
}
```

## 异常中断机制

```
try{
    System.out.println("第1行");
    int num=1/0;
    System.out.println("第2行");
    System.out.println("第3行");
}catch(Exception e){
    e.printStackTrace();
}
```

出现异常后就中断，后面语句不再执行

<b>因此存在多个catch的时候，catch的顺序非常重要：子类必须写在前面</b>

## 恢复机制

finally代码块

```
try{
    //被捕捉的代码
}catch(/*异常类型*/ e){
    //对异常的处理
}finally{
    //最后一定会执行的代码
}
```

所有try-catch执行完后，运行finally语句，无论程序是否发生异常，程序都会运行finally语句

finally块一般都会得到执行，它相当于一个万能的保险，但有四种特殊情况finally将不会执行

- finally块中发生异常
- 在前面的代码中用了System.exit()（强制停止当前程序）
- 程序所在线程死亡（代码执行前，程序停止或者结束）
- 关闭CPU

## 常见异常

# 在方法中抛出异常

## 异常的传播

当某个方法抛出了异常时，如果当前方法没有捕获异常，异常会被抛到上层调用方法，直到遇到某个try-catch被捕获为止

通过`printStackTrace()`可以打印出方法的调用栈：

```
java.lang.NumberFormatException: null
    at java.base/java.lang.Integer.parseInt(Integer.java:614)
    at java.base/java.lang.Integer.parseInt(Integer.java:770)
    at Main.process2(Main.java:16)
    at Main.process1(Main.java:12)
    at Main.main(Main.java:5)
```

## 抛出异常

### 使用throw关键字抛出异常

手动创造一个异常

throw new异常类型();例：

```
if(count<0){
    throw new ArithmeticException("人员数量是负数："+count);
}
throw关键字还可以更改异常
try{
    int a=1,b=0;
    if(b==0){
        throw new NullPointerException("b等于0，发生了")
    }
    int c=a/b;
}catch(Exception e){
    e.printStackTrace();
}
//输出为NullPointerException
```

通过printStackTrace()可以打印出方法的调用栈

### 使用throws关键字抛出异常

将异常交给别人来处理

public void method() throws 异常类型1，异常类型2...异常类型n{

    

}

如果将可能发生的异常写在throws后面，方法中可以不用try-catch1语句捕获异常

如果方法在外部的代码被调用时，则必须对该方法进行异常捕捉

```
try{
    method();
}catch(异常类型e){
    e.printStackTrace();
}
```

例：

```
public static void show() throws InterruptedException{
    for(int i=0;i<10;i++){
        System.out.println(i);
        Thread.sleep(1000);//休眠1秒
    }
}
public static void main(String[] arge){
    try{
        show();
    }catch(InterruptedException e){
        e.printStackTrace();
    }
}
```

### 异常屏蔽

```
public class Main {
    public static void main(String[] args) {
        try {
            Integer.parseInt("abc");
        }catch(Exception e) {
            System.out.println("catched");
            throw new RuntimeException(e);
        }finally {
            System.out.println("finally");
            throw new IllegalArgumentException();
        }
    }
}
```

finally抛出异常后，原来在catch中准备抛出的异常就“消失”了，因为<b>只能抛出一个异常</b>。没有被抛出的异常称为“被屏蔽”的异常。

当我们需要获知所有的异常时，可以先用origin变量保存原始异常，然后调用Throwable.addSuppressed(),把原始异常添加进来，最后在finally抛出。

<b>通过Throwable.addSuppressed()可以获取左右的Suppressed Exception。</b>

# 自定义异常

## 创建自定义异常

自己创建一个API中没有的异常

class 自定义异常 extends 已有的异常类{

    

}

例：

```
public class Main(){
    public static void main(String[] args){
        String playerType="monkey";
        try{
            if(!playerType.equals("human")){
                throw new NonHumanException("有非人类选手，"+playerType;)
            }
            System.out.println("开始比赛");
        }catch(NonHumanException e){
            e.printStackTrace();
        }
    }
}
class NonHumanException extends Exception{
    public NonHumanException(String message){
        super(message);
    }
}
```

进一步修改，使其弹出错误提示对话框：

```
public class Main(){
    public static void main(String[] args){
        String playerType="monkey";
        try{
            if(!playerType.equals("human")){
                throw new NonHumanException("有非人类选手，"+playerType);
            }
            System.out.println("开始比赛");
        }catch(NonHumanException e){
            e.printStackTrace();
        }
    }
}
class NonHumanException extends Exception{
    String message;
    public NonHumanException(String message){
        super(message);
        this.message=message;
    }
    public void printStackTrace(){
        super.printStackTrace();
        JOptionPane.showMessageDialog(null,message(异常日志),"发生异常"(对话框标题),JOptionPane.ERROR_MESSAGE);
    }
}
```

# 异常的使用原则

- 编写异常时不要乱抛异常，不能解决的再抛出
- 不要忽略捕捉到的异常，捕捉到异常及时处理
- 不要过度使用异常
- 不要使用过于庞大的try-catch块
- 子类抛出的异常必须包含在父类抛出的异常之内
- <b>特例：RuntimeException异常及其子类不受此原则约束</b>

# 断言

断言(Assertion)是一种调试程序的方式，使用assert关键字来实现断言。

例：

```
public static void main(String[] args){
    double x=Math.abs(-123.45);
    assert x>=0;
    System.out.println(x);
}
```

断言条件为true则继续运行程序，如果为false则抛出AssertionError。

使用assert语句时，还可以添加一个可选的断言消息：

assert x&gt;=0:"x must &gt;= 0";

断言失败的时候AssertionError会带上信息x must &gt;= 0.

# JDK Logging

调试代码时可以使用日志(Logging)代替反复使用System.out.println()语句进行测试。

Java标准库内置了日志包<b>java.util.logging</b>

JDK的日志定义了7个级别，从严重到普通：

- SEVERE
- WARNING
- INFO
- CONFIG
- FINE
- FINER
- FINEST

<b>INFO是默认级别，INFO级别以下的日志不会被打印出来</b>

例：

```
import java.util.logging.Logger;

public class Main {
    public static void main(String[] args) {
        Logger logger=Logger.getGlobal();
        logger.info("start process...");
        logger.warning("memory is running out...");
        logger.fine("ugnored");
        logger.severe("process will be terminated...");
    }
}
```

使用日志的好处：

- 可以设置输出样式，避免每次都写"ERROR："+var;
- 可以设置输出级别，禁止某些级别输出。例如，只输出错误日志；
- 可以被重定向到文件，这样可以在程序运行结束后查看日志；
- 可以按包名控制日志级别，只输出某些包打的日志；

局限：Logging系统在JVM启动时读取配置文件并完成初始化，一旦开始运行main()方法就无法修改配置；配置不太方便，需要在JVM启动时传递参数-Djava.util.logging.config.file=&lt;config-file-name&gt;。

# Commons Logging

Commons Logging是一个第三方日志库，它是由Apache创建的日志模块。

特色：可以挂接不同的日志系统，并通过配置文件指定挂接的日志系统。默认情况下，Commons Logging自动搜索并使用Log4j，如果没有找到，再使用JDK Logging。

使用Commons Logging只需要和两个类打交道：

第一步，通过LogFactory获取Log类的实例；

第二部，使用Log实例的方法打日志。

例：

```
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class Main {
    public static void main(String[] args) {
        Log log=LogFactory.getLog(Main.class);
        log.info("start...");
        log.warn("end.");
    }
}
```

要运行上述代码需要先下载Commons Logging。

Commons Logging定义了6个日志级别：

- FATAL
- ERROR
- WARNING
- INFO
- DEBUG
- TRACE

<b>默认级别是INFO</b>

如果在静态方法中引用Log，通常直接定义一个静态类型变量：

```
//在静态方法中引用Log:
public class Main{
    static final Log log=LogFactory.getLog(Main.class);
    static void foo(){
        log.info("foo");
    }
}
```

在实例方法中引用Log，通常定义一个实例变量：

```
//在实例方法中引用Log:
public class Person{
    protected final Log log=LogFactory.getLog(getClass());
    void foo(){
        log.info("foo");
    }
}
```

<b>注意：实例变量的获取方法是LogFactory.getLog(getClass())，用这种方式子类可以直接使用该实例</b>

例：

```
//在子类中使用父类实例化的log:
public class Student extends Person{
    void bar(){
        [log.info](http://log.info)("bar");
    }
}
```

Commons Logging的日志方法，例如info()，除了info(String)还有info(String, Throwable)

例：

```
try{
    ...
}catch(Exception e){
    log.error("got exception!",e);
}
```

